#' Class definition for the CDS package
#'
#' @name CDS
#' @aliases CDS,CDS-class
#' @docType class
#' @rdname CDS-class
#' @export
#' 

setOldClass("Date", S4Class = "Date")

setClass("CDS",
         representation = representation(
             contract = "character",
             entityName = "character",
             RED = "character",
             TDate = "Date",
             baseDate = "Date",
             currency = "character",
             types = "character",
             rates = "numeric",
             expiries = "character",
             mmDCC = "character",
             fixedSwapFreq = "character",
             floatSwapFreq = "character",
             fixedSwapDCC = "character",
             floatSwapDCC = "character",
             badDayConvZC = "character",
             holidays = "character",
             valueDate = "Date",
             benchmarkDate = "Date",
             startDate = "Date",
             endDate = "Date",
             stepinDate = "Date",
             backstopDate = "Date",
             firstcouponDate = "Date",
             pencouponDate = "Date",
             maturity = "character",
             dccCDS = "character",
             freqCDS ="character",
             stubCDS ="character",
             badDayConvCDS ="character",
             calendar = "character",
             
             parSpread = "numeric",
             couponRate = "numeric",
             recoveryRate = "numeric",
             inputPriceClean = "logical",
             notional = "numeric",
             payAccruedOnDefault = "logical",

             principal = "numeric",
             accrual = "numeric",
             upfront = "numeric",
             ptsUpfront = "numeric",
             spreadDV01 = "numeric",
             IRDV01 = "numeric",
             RecRisk01 = "numeric",
             defaultProb = "numeric",
             defaultExpo = "numeric",
             price = "numeric"
             ),
         prototype = prototype(
             contract = character(),
             entityName = character(),
             RED = character(),
             TDate = character(),
             baseDate = character(),
             currency = character(),
             types = character(),
             rates = numeric(),
             expiries = character(),
             mmDCC = character(),
             fixedSwapFreq = character(),
             floatSwapFreq = character(),
             fixedSwapDCC = character(),
             floatSwapDCC = character(),
             badDayConvZC = character(),
             holidays = character(),
             valueDate = character(),
             benchmarkDate = character(),
             startDate = character(),
             endDate = character(),
             stepinDate = character(),
             backstopDate = character(),
             firstcouponDate = character(),
             pencouponDate = character(),
             maturity = character(),
             dccCDS = character(),
             freqCDS =character(),
             stubCDS =character(),
             badDayConvCDS =character(),
             calendar = character(),
             parSpread = numeric(),
             couponRate = numeric(),
             recoveryRate = numeric(),
             inputPriceClean = logical(),
             notional = numeric(),
             payAccruedOnDefault = logical(),
             principal = numeric(),
             accrual = numeric(),
             upfront = numeric(),
             ptsUpfront = numeric(),
             spreadDV01 = numeric(),
             IRDV01 = numeric(),
             RecRisk01 = numeric(),
             defaultProb = numeric(),
             defaultExpo = numeric(),
             price = numeric()
             )
         )

